# Use trusty for newer graphviz
sudo: required
dist: trusty

language: python

python:
# https://github.com/travis-ci/travis-ci/issues/2219
- "3.4_with_system_site_packages"

addons:
  apt:
    packages:
    - gir1.2-gtk-3.0
    - python3-gi
    - python3-gi-cairo
    - graphviz
    - xvfb

before_install:
- dot -V

script:
- cd tests
- xvfb-run -a -s '-screen 0 1024x768x24' python ../test.py *.dot graphs/*.gv

# https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: jrfonseca
  password:
    secure: WJOfZYkpzmG62sHgoBb66TDGeFHP/KNGrwl/ul8Q22SdFCr5u3gpmQ8bHGgV3fXk/onuDPC3gJxcLpH5+MeZEHiS+pL+gP5XbtiEGOXPe8N2I3eIffO4gHnx1naC5stdk8v44SAY/9pw+CGBOHDJXWMeMDM/QEWo7bpHsZkpRZI=
  on:
    tags: true
    distributions: sdist
    repo: jrfonseca/xdot.py
